name: Update Markdown with Dataset Info

# This runs the workflow when a push event occurs but only for changes to specific paths
on:
  push:
    paths:
      - 'high_value_datasets.xlsx'  # Only run when this file changes

jobs:
  update-markdown:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas requests openpyxl

      - name: Run the Python script
        env:
          CKAN_API_KEY: ${{ secrets.CKAN_API_KEY }}
        run: |
          python get_dataset_details.py

      - name: Commit changes
        run: |
          git config --local user.email "sudham.surya@gmail.com"
          git config --local user.name "suryakandukuri"
          git add docs/index.md
          git commit -m "Update docs/index.md with latest API data"
          git push
